# -*- coding: utf-8 -*-
"""17/8/26/ 24ajla4220

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaUjoMmi4p6qE8HSppV9m4N5gB_jX71d
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
#step 1:load dataset
diabetes = datasets.load_diabetes()
#ues one feature(BMI) for Simplocity
x = diabetes.data[:,np.newaxis,2]
y = diabetes.target
#step 2:split into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size=0.2,random_state=42
)
#step 3:train linear regression model
model = LinearRegression()
model.fit(x_train,y_train)
#step 4:make predictions
y_pred = model.predict(x_test)
#step 5:evaluate model
print("mean squared error:",mean_squared_error(y_test, y_pred))
print("R^2 score:",r2_score(y_test,y_pred))
#step 6: plot results
plt.scatter(x_test,y_test,color='black',label="Actual data")
plt.plot(x_test,y_pred,color='blue',linewidth=2,label="Regression line")
plt.xlabel("BMI")
plt.ylabel("Diabetes Progression score")
plt.legend()
plt.show()